Update: qt 6.8.4, ccache 4.14, Debian Forky (#15)
* Update: qt_6.8.4 LTS LGPL, ccache 4.14

* Update Debian scripts

* Update Debian scripts (2)

* Update Debian scripts (3)

* Update Debian scripts (4)

* Update Debian scripts (5)

* Update Debian scripts (6)

* Update Debian scripts (7)

* Update Debian scripts (8)

* Update Debian scripts (9)

* Update Debian scripts (10)

* Update Debian scripts (11)

* Update Debian scripts (12)

* Update Fedora

* test

* Update build.sh

* Update build.sh

* Update

* Update buildDebian

* Update buildDebian

* Update buildDebian

* Update buildDebian

* Update push.yml

* Update buildDebian

* Update buildDebian

* Update buildDebian

* Update buildDebian

diff --git a/buildDebian b/buildDebian
--- a/buildDebian
+++ b/buildDebian
@@ -3,26 +3,38 @@ FROM ${DOCKER_SOURCE}
 
 # install the packages required by HyperHDR
 ARG DOCKER_SOURCE
-RUN apt-get update
-RUN bash -c 'if [[ "${DOCKER_SOURCE}" == arm64* ]] || [[ "${DOCKER_SOURCE}" == arm32* ]]; then \
-        apt-get install -y --no-install-recommends curl gnupg ca-certificates && update-ca-certificates && \
-        . /etc/os-release && \
-        curl -fsSL "https://github.com/raspberrypi/rpi-image-gen/raw/master/keydir/raspberrypi-archive-keyring.gpg" | gpg --dearmor -o /usr/share/keyrings/raspberrypi-archive-keyring.gpg && \
-        echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] http://archive.raspberrypi.org/debian/ ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/raspberrypi.list && \
-        echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] http://archive.raspberrypi.org/debian-security ${VERSION_CODENAME}/security main" >> /etc/apt/sources.list.d/raspberrypi.list > /etc/apt/sources.list && \
-        > /etc/apt/sources.list && \
-        rm -rf /var/lib/apt/lists/* && \
-        apt-get update && \
-        apt-get full-upgrade -y && \
-        (apt-get install -y --no-install-recommends libcec-dev libp8-platform-dev raspi-utils-dt raspi-utils-core libdtovl0 libdrm-dev || true) && \
+RUN bash -c ' \
+    if [[ "${DOCKER_SOURCE}" == *bullseye* ]]; then \
+        echo "Switch Debian Bullseye (EOL) to archive and synchronize..."; \
+        echo "deb http://archive.debian.org/debian bullseye main" > /etc/apt/sources.list; \
+        echo "Acquire::Check-Valid-Until \"false\";" > /etc/apt/apt.conf.d/99no-check-valid-until; \
+        echo -e "Package: *\nPin: origin \"archive.debian.org\"\nPin-Priority: 1001" > /etc/apt/preferences.d/99downgrade; \
+        apt-get update && apt-get dist-upgrade -y --allow-downgrades; \
+    else \
+        apt-get update; \
+    fi; \
+    \
+    if [[ "${DOCKER_SOURCE}" == arm64* ]] || [[ "${DOCKER_SOURCE}" == arm32* ]]; then \
+        apt-get install -y --no-install-recommends curl gnupg ca-certificates; \
+        update-ca-certificates; \
+        . /etc/os-release; \
+        curl -fsSL "https://github.com/raspberrypi/rpi-image-gen/raw/master/keydir/raspberrypi-archive-keyring.gpg" | gpg --dearmor -o /usr/share/keyrings/raspberrypi-archive-keyring.gpg; \
+        echo "deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] http://archive.raspberrypi.com/debian/ ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/raspberrypi.list; \
+        apt-get update; \
+        (apt-get install -y --no-install-recommends raspi-utils-dt raspi-utils-core libdtovl0 || true); \
         (apt-get install -y --no-install-recommends mesa-vulkan-drivers || true); \
+        if [[ "${DOCKER_SOURCE}" == *bullseye* ]]; then \
+            (apt-get install -y --no-install-recommends libraspberrypi-bin libraspberrypi-dev || true); \
+        fi; \        
     else \
         echo "Skipping Raspberry Pi OS repository, docker source is ${DOCKER_SOURCE}"; \
-    fi'
-
-# install the packages required by HyperHDR
-RUN apt-get upgrade -y
-RUN apt-get install -y \
+    fi; \
+    \
+    echo "Install the packages required by HyperHDR"; \
+    \
+    apt-get install -y libcec-dev libp8-platform-dev libdrm-dev || true; \
+    \
+    apt-get install -y \
     build-essential \
     cmake \
     flatbuffers-compiler \
@@ -44,15 +56,20 @@ RUN apt-get install -y \
     libusb-1.0-0-dev \
     libx11-dev \
     libzstd-dev \
-    lld \    
+    lld \
     ninja-build \
     patchelf \
     pkg-config \
     python3 \
     unzip \
-    wget
-
-RUN apt --assume-yes install libcec-dev libp8-platform-dev || true
+    wget; \
+    \
+    if [[ "${DOCKER_SOURCE}" == *bullseye* ]]; then \
+        echo "Updating cmake..."; \
+        apt-get remove -y cmake cmake-data; \
+        apt-get install -y python3-pip; \
+        pip3 install cmake --upgrade; \
+    fi;'
 
 RUN mkdir -p /scripts
 COPY build.sh /scripts
